services:
  - type: web
    name: farmart-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: JWT_SECRET_KEY
        value: your-jwt-secret
      - key: MAIL_USERNAME
        value: farmart597@gmail.com
      - key: MAIL_PASSWORD
        value: your-app-password
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: DEV_DATABASE_URL
        value: your-postgres-url
    autoDeploy: true
    region: oregon
