"""added location to Animals

Revision ID: 32133db7c7ba
Revises: 9fbb2eb8cad4
Create Date: 2025-07-25 22:40:24.063013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32133db7c7ba'
down_revision = '9fbb2eb8cad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
