"""Change animal_id in AnimalImage to String(36)

Revision ID: 629bc46e229e
Revises: 326cee4faee6
Create Date: 2025-07-17 19:23:18.170371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629bc46e229e'
down_revision = '326cee4faee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_images', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('animal_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_images', schema=None) as batch_op:
        batch_op.alter_column('animal_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
