"""migration after adding pickup station and payment method to Order

Revision ID: 9756e345cb3a
Revises: 629bc46e229e
Create Date: 2025-07-18 16:28:19.589747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9756e345cb3a'
down_revision = '629bc46e229e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_station', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('pickup_station')

    # ### end Alembic commands ###
