"""added delivery_method to Orders

Revision ID: 9fbb2eb8cad4
Revises: 128d7654e8b0
Create Date: 2025-07-25 22:37:59.719180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fbb2eb8cad4'
down_revision = '128d7654e8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_method', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_method')

    # ### end Alembic commands ###
