"""Add farmer_id to OrderItem

Revision ID: c10948cae788
Revises: 30afd3e4ddb4
Create Date: 2025-07-26 23:08:02.956477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10948cae788'
down_revision = '30afd3e4ddb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', sa.String(), nullable=True),)
        batch_op.alter_column('order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('animal_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'farmers', ['farmer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('animal_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('farmer_id')

    # ### end Alembic commands ###
