"""added role to farmer model

Revision ID: f601e5208af6
Revises: 5757443fb225
Create Date: 2025-08-01 03:18:02.999932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f601e5208af6'
down_revision = '5757443fb225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_images', schema=None) as batch_op:
        batch_op.drop_constraint('fk_animal_images_animal_id', type_='foreignkey')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint('fk_animals_farmer_id', type_='foreignkey')

    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), server_default='farmer', nullable=False))


    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedback_user_id', type_='foreignkey')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',existing_type=sa.UUID(),
        type_=sa.Integer(),
        existing_nullable=False)
        batch_op.alter_column('farmer_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('farmer_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_feedback_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_animals_farmer_id', 'farmers', ['farmer_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('farmer_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('animal_images', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_animal_images_animal_id', 'animals', ['animal_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
